### ISSUE TITLE
Definir todas as tarefas necessárias

### ISSUE THREAD

**Issue by wladrbarbosa** [wladrbarbosa/JogoTCC#2]
```yaml
start_date: 2021/09/03
due_date: 2021/09/03
progress: 0.1
parent: 0
```
