### ISSUE TITLE
Difinir os 5 objetos coletáveis

### ISSUE THREAD

**Issue by wladrbarbosa** [wladrbarbosa/JogoTCC#24]
```yaml
start_date: 2021/09/15
due_date: 2021/09/15
progress: 0.1
parent: 0
```
