### ISSUE TITLE
Definir falas iniciais da analista

### ISSUE THREAD

**Issue by wladrbarbosa** [wladrbarbosa/JogoTCC#26]
```yaml
start_date: 2021/09/06
due_date: 2021/09/07
progress: 0.1
parent: 0
```
