### ISSUE TITLE
Definir cronograma

### ISSUE THREAD

**Issue by wladrbarbosa** [wladrbarbosa/JogoTCC#3]
```yaml
start_date: 2021/09/04
due_date: 2021/09/05
progress: 0.1
parent: 0
```
