### ISSUE TITLE
Criar sala do enigma 1

### ISSUE THREAD

**Issue by wladrbarbosa** [wladrbarbosa/JogoTCC#30]
```yaml
start_date: 2021/09/19
due_date: 2021/09/21
progress: 0.1
parent: 0
```
