### ISSUE TITLE
Cria a UI de gameplay

### ISSUE THREAD

**Issue by wladrbarbosa** [wladrbarbosa/JogoTCC#35]
```yaml
start_date: 2021/10/02
due_date: 2021/10/03
progress: 0.0
parent: 0
```
