### ISSUE TITLE
Criar raio da tempestade

### ISSUE THREAD

**Issue by wladrbarbosa** [wladrbarbosa/JogoTCC#36]
```yaml
start_date: 2021/09/03
due_date: 2021/09/03
progress: 0.0
parent: 0
```
