### ISSUE TITLE
Definir modelo do protagonista

### ISSUE THREAD

**Issue by wladrbarbosa** [wladrbarbosa/JogoTCC#4]
```yaml
start_date: 2021/09/22
due_date: 2021/09/22
progress: 0
parent: 0
```
