### ISSUE TITLE
Criar chuva

### ISSUE THREAD

**Issue by wladrbarbosa** [wladrbarbosa/JogoTCC#41]
```yaml
start_date: 2021/09/11
due_date: 2021/09/11
progress: 0.0
parent: 0
```
