### ISSUE TITLE
Implementar movimentação do protagonista

### ISSUE THREAD

**Issue by wladrbarbosa** [wladrbarbosa/JogoTCC#42]
```yaml
start_date: 2021/09/24
due_date: 2021/10/02
progress: 0.0
parent: 0
```
