### ISSUE TITLE
Implementar enigma da sala 1

### ISSUE THREAD

**Issue by wladrbarbosa** [wladrbarbosa/JogoTCC#44]
```yaml
start_date: 2021/09/20
due_date: 2021/09/21
progress: 0.0
parent: 0
```
