### ISSUE TITLE
Gerar versão alpha

### ISSUE THREAD

**Issue by wladrbarbosa** [wladrbarbosa/JogoTCC#49]
```yaml
start_date: 2021/10/05
due_date: 2021/10/05
progress: 0.0
parent: 0
```
